name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Debug Root Directory Contents
      run: ls -l

    - name: Check if backend folder exists
      id: check_backend
      run: |
        if test -d backend; then
          echo "::set-output name=result::found"
          echo "Backend folder found."
        else
          echo "::set-output name=result::not found"
          echo "Backend folder not found."
        fi
    
    - name: Debug Backend Folder Contents
      if: steps.check_backend.outputs.result == 'found'
      run: ls -l backend
    
    - name: Change directory to backend
      if: steps.check_backend.outputs.result == 'found'
      run: cd backend && pwd

    - name: Install dependencies
      if: steps.check_backend.outputs.result == 'found'
      run: npm ci

    - name: Build project
      if: steps.check_backend.outputs.result == 'found'
      run: npm run build --if-present

    - name: Debug Before Running Tests
      if: steps.check_backend.outputs.result == 'found'
      run: echo "About to run tests"

    - name: Run tests
      if: steps.check_backend.outputs.result == 'found'
      run: npm test

    - name: Debug After Running Tests
      if: steps.check_backend.outputs.result == 'found'
      run: echo "Tests have been run"
