name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Debug Root Directory Contents
      run: ls -l
    - name: Check if backend folder exists
      run: test -d backend && echo "Backend folder found" || echo "Backend folder not found"
      id: check_backend
    - name: Debug Backend Folder Contents
      run: ls -l backend
      if: steps.check_backend.outputs.result == 'Backend folder found'
    - name: Change directory to backend
      run: cd backend
      if: steps.check_backend.outputs.result == 'Backend folder found'
    - name: Debug Current Directory
      run: pwd
      if: steps.check_backend.outputs.result == 'Backend folder found'
    - run: npm ci
      if: steps.check_backend.outputs.result == 'Backend folder found'
    - run: npm run build --if-present
      if: steps.check_backend.outputs.result == 'Backend folder found'
    - name: Debug Before Running Tests
      run: echo "About to run tests"
      if: steps.check_backend.outputs.result == 'Backend folder found'
    - run: npm test
      if: steps.check_backend.outputs.result == 'Backend folder found'
    - name: Debug After Running Tests
      run: echo "Tests have been run"
      if: steps.check_backend.outputs.result == 'Backend folder found'
